### ISSUE TITLE
chroot: failed to run command '/usr/bin/env': No such file or directory

### ISSUE THREAD

**Issue by rsaphala** [siderolabs/talos#11469]
### Description

When deploying Nutanix CSI on Talos OS, the CSI node plugin fails to mount volumes because the binary /usr/bin/env is missing from the Talos host. This causes all chroot operations (required by the CSI plugin to run tools like iscsiadm) to fail, blocking persistent volume support for Nutanix on Talos.

### Logs

CSI pod log example:

```
2025-07-30T10:32:38.66Z util.go:364: [INFO] iscsi: Running cmd: iscsiadm with args: [-m iface -I default -o show]
2025-07-30T10:32:38.664Z util.go:371: [ERROR] iscsi: Failed to run cmd iscsiadm with args [-m iface -I default -o show] with error: exit status 127, chroot: failed to run command '/usr/bin/env': No such file or directory
2025-07-30T10:32:38.664Z iscsi_util.go:405: [ERROR] iscsi: could not read iface default error: chroot: failed to run command '/usr/bin/env': No such file or directory
2025-07-30T10:32:38.664Z iscsi_util.go:607: [ERROR] iscsi/lvm: err: exit status 127
2025-07-30T10:32:38.665Z nodeserver.go:239: [INFO] nutanix: error: iscsi/lvm failure, last err seen:
exit status 127
2025-07-30T10:32:38.665Z util.go:461: [INFO] function: NodePublish for cfbfabf8-f5f4-4f08-5d63-0ce70ef19f90 took 193.295985ms
2025-07-30T10:32:38.665Z node.go:161: [ERROR] NodePublishVolume returned error for volume: NutanixVolumes-cfbfabf8-f5f4-4f08-5d63-0ce70ef19f90, err: rpc error: code = Internal desc = iscsi/lvm failure, last err seen:
exit status 127
E0730 10:32:38.665040      18 utils.go:31] GRPC error: rpc error: code = Internal desc = iscsi/lvm failure, last err seen:
exit status 127
```

Talos node check:

```
talosctl -n 10.25.102.21 ls /usr/bin/env
NODE   NAME
1 error occurred:
 rpc error: code = Unknown desc = lstat /usr/bin/env: no such file or directory
```

### Environment
Talos version: 1.10.5
Kubernetes version: 1.33.2
Nutanix AHV (Prism Central) & Sidero Omni

Workarounds Tried
	•	Verified /usr/bin/env exists inside the CSI container, but not in the host’s root.
	•	Attempted to add util-linux-tools and iscsi-tools extensions to Talos; /usr/bin/env still missing.

A supported extension or inclusion of /usr/bin/env in util-linux-tools / other extensions would resolve this issue for all Talos+CSI users.

**Comment by smira** [comment]
Talos doesn't have shell or any shell-related stuff like `/usr/bin/env` on the host, and there is no plan to add that.

CSI should be fixed to avoid relying on host binaries this way.

**Comment by rsaphala** [comment]
@smira What's the best way to handle this? The CSI code is closed source

**Comment by smira** [comment]
If you're a customer of Nutanix, you can ask them to fix it?

**Comment by rsaphala** [comment]
Would an extension work in this case? I've tried creating one but the env binary is still not found
I've created an additional issue here: https://github.com/siderolabs/omni/issues/1386

**Comment by smira** [comment]
Extensions are not allowed to append to `/usr/bin`.

**Comment by tomfriedhof** [comment]
This is also an issue when attempting to use the Synology CSI as documented here: https://docs.siderolabs.com/kubernetes-guides/csi/synology-csi#run-performance-tests

The pod fails to mount with this error:

```
MountVolume.MountDevice failed for volume "pvc-9c255fd4-1c4e-4d41-a944-dfd7a0e7e2e0" : rpc error: code = Internal desc = rpc error: code = Internal desc = Failed to login with target iqn [iqn.2000-01.com.synology:Synology.pvc-9c255fd4-1c4e-4d41-a944-dfd7a0e7e2e0], err: chroot: can't execute '/usr/bin/env': No such file or directory
```

**Comment by tomfriedhof** [comment]
I ended up using his repo instead to get things working https://github.com/QuadmanSWE/synology-csi-talos. The repo referenced from the talos documentation seems to be out of date.

**Comment by kaasszje** [comment]
> I ended up using his repo instead to get things working https://github.com/QuadmanSWE/synology-csi-talos. The repo referenced from the talos documentation seems to be out of date.

Thank you so much, you saved my day (week even)

**Comment by sykloid** [comment]
> I ended up using his repo instead to get things working https://github.com/QuadmanSWE/synology-csi-talos. The repo referenced from the talos documentation seems to be out of date.

Indeed, I can confirm that this works -- using the helm chart within the `deploy/` directory of that repository, and the image referenced in the README which was pushed to docker hub.

**Comment by badnetmask** [comment]
> Talos doesn't have shell or any shell-related stuff like `/usr/bin/env` on the host, and there is no plan to add that.
> 
> CSI should be fixed to avoid relying on host binaries this way.

The Synology CSI Driver added support for the `--iscsiadm-path` [in version 1.2.1](https://github.com/SynologyOpenSource/synology-csi/pull/85), which fixes this particular problem. I have also sent a[ PR to update the Helm Chart](https://github.com/christian-schlichtherle/synology-csi-chart/pull/28) to reflect that change.

I think Sidero can switch back to suggest using the official driver in the documentation, since the maintainer of the fork suggested in the docs already [declared they're no longer maintaining it](https://github.com/zebernst/synology-csi-talos/issues/21#issuecomment-3378839624).

**Comment by sykloid** [comment]
@badnetmask would you consider submitting that directly to the upstream synology repo for changes to the chart?

**Comment by badnetmask** [comment]
> [@badnetmask](https://github.com/badnetmask) would you consider submitting that directly to the upstream synology repo for changes to the chart?

I'm honestly having a hard time understanding who holds the upstream Helm chart. Looking at the [synology-csi Helm's README.md](https://github.com/SynologyOpenSource/synology-csi/blob/main/deploy/helm/README.md) it points to the chart that I patched owned by a community member, and I cannot see where this repo's chart is published. The [main CSI repo README.md](https://github.com/SynologyOpenSource/synology-csi/blob/main/README.md) suggests the Helm charts are supposed to be used for development only, and they are not published anywhere.

Nevertheless, someone already [sent a PR to the upstream repo](https://github.com/SynologyOpenSource/synology-csi/pull/110).

**Comment by JanBenisek** [comment]
Just want to thank y'all, I got stuck on this for a good few hours, would't have solved it without you!
If someone gets here, what helped me:
- Click your installation in [talos factory](https://factory.talos.dev/)
```yaml
# I got these
customization:
  systemExtensions:
    officialExtensions:
      - siderolabs/btrfs
      - siderolabs/iscsi-tools
      - siderolabs/util-linux-tools
```
- One needs to run `t upgrade -n kevin --image factory.talos.dev/metal-installer/123:v1.11.6` to get it in place, reboot.
- Confirm:
```shell
t get extensions -n kevin
```
- Then follow the fantastic instruction in the repo: https://github.com/QuadmanSWE/synology-csi-talos
  - For myself, I copied the code to my repo and patched it with my container and the extra commands:
```yaml
# node.yaml
- name: csi-plugin
          securityContext:
            privileged: true
          imagePullPolicy: IfNotPresent
          image: ghcr.io/janbenisek/synology-csi:v1.2.1
          args:
            - --nodeid=$(KUBE_NODE_NAME)
            - --endpoint=$(CSI_ENDPOINT)
            - --client-info
            - /etc/synology/client-info.yml
            - --log-level=debug
            # Patch from https://github.com/siderolabs/talos/issues/11469
            - '--chroot-dir=/host'
            - '--iscsiadm-path=/usr/local/sbin/iscsiadm'
```   
- Make sure it is all synced.
- In my case, I am using synology with DSM 7 so somehow I had to use `https`, it did not work on `http` (could haven been a fluke)
```yaml
clients:
- host: 192.168.178.96  
  port: 5001
  https: true
  username: bot_k8s
  password: PWD
```
- If you are using `nfs`, make sure it is allowed, it has permissions and there is storage pool -> volume -> shared folder.

**Comment by steverfrancis** [comment]
closing this as not planned for architectural reasons.

Talos host doesn't ship /usr/bin/env or any other shell tooling, by design.
The fix lives in the CSI plugin, not in Talos. 

The minimal, immutable, non-shell-bearing host is most of what makes Talos Talos — it's the property that delivers the security, reproducibility, and reduced attack surface customers choose Talos for. CSI plugins that chroot into the host and invoke shell binaries (/usr/bin/env, iscsiadm wrappers, etc.) are written against the assumption of a conventional Linux host, and weak security. That is not Talos.

Synology CSI — this has been fixed. https://github.com/SynologyOpenSource/synology-csi/pull/85

Nutanix CSI — closed source, so the fix has to come from Nutanix. If you're a Nutanix customer, please open a support case with them citing this thread. The change they need to make is the same shape as the Synology community fork: run the iSCSI tooling inside the CSI plugin's own container rather than chrooting into the host. We're happy to consult on the technical pattern if Nutanix engineering wants to engage directly.

Any other CSI hitting this pattern — same playbook. Either pick a Talos-aware CSI (Longhorn, Rook-Ceph, Piraeus, etc. — they don't chroot-to-host), or work with the vendor / community to drop the chroot pattern. The Synology fork is a clean reference implementation.

Closing as architecturally-out-of-scope.
